<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="NEWT-PBS174" name="com.pagefactory.testcases.SignOut" tests="1" failures="0" timestamp="31 May 2018 11:38:52 GMT" time="0.000" errors="1">
  <testcase name="logout" time="0.000" classname="com.pagefactory.testcases.SignOut">
    <error type="java.lang.Throwable" message="Method SignOut.logout()[pri:0, instance:com.pagefactory.testcases.SignOut@7085bdee] depends on not successfully finished methods in group &quot;booking&quot;">
      <![CDATA[java.lang.Throwable: Method SignOut.logout()[pri:0, instance:com.pagefactory.testcases.SignOut@7085bdee] depends on not successfully finished methods in group "booking"
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1037)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- logout -->
</testsuite> <!-- com.pagefactory.testcases.SignOut -->
